### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by LorenzMeier** [bbatsche/Sample-Gitbook#3]
Hi,

I would love to steal some of your content for documentation of an Open Source project. Could you clarify the license of your sample? I would have a slight preference for CC-BY (without SA) since its flexible and has attribution (CC-Zero also would work). CC-BY-SA would be workable, but complicate things.

**Comment by bbatsche** [comment]
Hi Lorenz,

First, thanks for asking about this. I really appreciate you taking the time to check with me about licensing terms. All in all, I'd say treating this content as CC-BY or MIT Licensed would be acceptable. I would also suggest you take a look at [Codeup Gitbook-Base](/gocodeup/Gitbook-Base) as that's a more up to date fork of this repo that my company and I are actively maintaining. Thanks again, and good luck!
